### ISSUE TITLE
How to Configure Geo Values

### ISSUE THREAD

**Issue by The4Syndicate** [github/octodns#107]
I am trying to configure dns for a GeoRouted Domain and I understand that I need to add the geo key under the record I am wanting to add it for. After that I should start listing the geo names as a key and an array of values after.

The question I have is what are all the possible Geo Names I can add to the file. I ask this because I tried adding the values I already had at Route53 and I get errors like what follows: 

- invalid geo "US-EAST-1"
- invalid geo "AP-SOUTH-1"
- invalid geo "US-WEST-1"

**Comment by ross** [comment]
> The question I have is what are all the possible Geo Names I can add to the file. I ask this because I tried adding the values I already had at Route53 and I get errors like what follows:
> 
> invalid geo "US-EAST-1"
> invalid geo "AP-SOUTH-1"
> invalid geo "US-WEST-1"

octoDNS's `geo` records are [geo location](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-geo) rather than proximty, which I believe your vaules may be for. That's a AWS-only concept and thus not something that's supported (or supportable) in octoDNS which tries to unify concepts supported by many/all providers. 

As for the values Route53's options are [here](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-values-geo.html#rrsets-values-geo-location). You'll need to combine both the continent and country codes. e.g. 

* `NA` - all of Noth America
* `NA-US` - the United States
* `NS-US-CA` - The state of California (sub-country support limited to the US)
