### ISSUE TITLE
Add support for DNS Made Easy

### ISSUE THREAD

**Issue by davidmmiller** [github/octodns#150]
Can you please look into supporting DNS Made Easy DNS?

http://www.dnsmadeeasy.com/integration/restapi/

**Comment by yzguy** [comment]
Will need to look into it. The sandbox thing might be adequate for building it, or maybe a 30 day trial.

It “should” be relatively easy if the API is decent.

**Comment by yzguy** [comment]
Totally do-able. I already started work on it. They have a pretty weird authentication scheme, but figured that out.

I think initially will probably just be records, then after Geo can be added later to the provider.

**Comment by oryagel** [comment]
I would love to see that as well. I'm in the process of migrating from DME just because they don't have OctoDNS provider.

**Comment by yzguy** [comment]
I have the "provider" relatively complete. DME has some quirks to deal with (Relative values, Cannot make NS record without there being an A record first, etc.) that I'm trying to deal with.

Then the rest would just be adding tests.

**Couple questions:**
Do you use ANAME records?
Do you use relative values?

**Comment by oryagel** [comment]
We don't have any ANAME records.
By relative values, do you mean domain records that points to the same domain without specifying the domain part? We try not to have these. In my opinion, you can ignore this case.

**Comment by yzguy** [comment]
Great. I'm probably not going to add in ANAME records because I think they are only specific to DNSMadeEasy.

As for relative, yes you're right on with your description. I'm handling it with dumping relative values, then making them absolute, so they will be absolute in the YAML. If you re-apply the YAML it will delete/create the record again with the absolute value. 

That delete/create behavior could be dicey, as there is a period where the record wouldn't exist.

**Comment by yzguy** [comment]
@ross Would like to bounce a couple questions/thoughts off you

1. DNSMadeEasy allows you to specify relative values, it returns them from the API as relative. Currently, I'm handling it with dumping relative values via the DnsMadeEasyClient, then making them absolute before returning them from the caller, so they will be absolute in the YAML. If you re-apply the YAML it will delete the relative record from the provider and create the record again with the absolute value.

This delete/create behavior could be dicey, as there is a period where the record wouldn't exist. Wondering if you would consider that acceptable and if a note just saying the behavior of the provider, so users are aware.

2. DNSMadeEasy will not allow you to create a NS record with a relative value if there is no A record already created for it. It will however allow you to create a NS record with an absolute value of a record in the same zone regardless if the A record exists. The latter is the behavior I have written in the client to force absolute values.

At the same time, you cannot delete an A record if an NS record is pointing at it by relative value (this might happen if it was created before using OctoDNS, etc). If OctoDNS ran and needed to change the value, then it would error, as it couldn't change it without deleting it first.

**Comment by ross** [comment]
> DNSMadeEasy allows you to specify relative values, it returns them from the API as relative. Currently, I'm handling it with dumping relative values via the DnsMadeEasyClient, then making them absolute before returning them to the caller, so they will be absolute in the YAML. If you re-apply the YAML it will delete the relative record from the provider and create the record again with the absolute value.

> This delete/create behavior could be dicey, as there is a period where the record wouldn't exist. Wondering if you would consider that acceptable and if a note just saying the behavior of the provider, so users are aware.

There are a couple providers' APIs that don't provide safe ways to update things where you have to delete before you can create. I have https://github.com/github/octodns/issues/144 to actually fix this for CloudFlare as they have an update API which needs to be used rather than delete and create. If the provider doesn't have an update (which atomically makes the change) I don't think there's much we can really do 😞 .

> Do you think that we should change OctoDNS to know how to take a relative value from a provider, make it absolute, then compare the absolute YAML value to it to determine if a change needs to take place? This would probably be a relatively easy change in the changes method of ValueMixin and ValuesMixin inside Record

Probably not tbh. I've tried to steer clear of leaking provider specifics into the core model of things. I think translating these is the right way to go since that makes them RFC compliant. Given the workflow of showing diffs before apply them it should be safe and clear what octoDNS is going to do to "fix" the records before people tell it to do so. The end user is always reviewing the changes and giving them the implicit 👍  by adding the `--doit` flag. 

> I can only think of adding in another exception to the client that is raised when the API responds saying the action is not allowed.

Is is possible to differentiate between there was a general error and I can't do that b/c it's being used? Seems like the best bet here is just to make the error message as clear as it's reasonably possible to make it.

**Comment by kylef** [comment]
> Great. I'm probably not going to add in ANAME records because I think they are only specific to DNSMadeEasy.

@yzguy DNSMadeEasy ANAME records (http://www.dnsmadeeasy.com/services/anamerecords/) are pretty similar, if not the same thing as an ALIAS record on other providers. Perhaps ALIAS records could be mapped to ANAME in OctoDNS for this particular provider?

**Comment by kylef** [comment]
@yzguy If you have a branch somewhere with DNSMadeEasy support, let me know where it is and I can give it a go and test it out.

**Comment by yzguy** [comment]
Hello,

https://github.com/yzguy/octodns/tree/dnsmadeeasy-provider

I meant to finish it up this weekend, but some stuff came up. I "think" the only things I need to add is  ANAME/Alias thing and looking into the Exception for trying to delete an A record when it's referenced by an NS record if possible, and tests.

Otherwise it's fully functional

**Comment by yzguy** [comment]
Adding note for myself:

If you trigger Rate Limiting you get a 400 response back, the body being `{error: ["Rate limit exceeded"]}`.

This body is not valid JSON, and request's `.json()` method throws a ValueError

```
  File "/Users/yzguy/dns_clients/dnsmadeeasy/dnsmadeeasy.py", line 24, in __init__
    self.build_message(resp.json()['error']))
  File "/Users/yzguy/dns_clients/venv/lib/python2.7/site-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

I opened a support ticket with DNSMadeEasy to see if they can address this, but presumably because I am not actually a customer/it's an existing API it might be a bigger deal than just making it valid JSON.

**Comment by yzguy** [comment]
@kylef I fixed up an issue with making relative values absolute, as well as adding a BadRequest exception that displays the error back from DNSMadeEasy.

Currently my branch is pointing to the Sandbox API.

**Comment by yzguy** [comment]
Need to add functionality from: https://github.com/github/octodns/pull/175
