### ISSUE TITLE
Add CAA support to Azure Provider

### ISSUE THREAD

**Issue by omerlh** [github/octodns#160]
Currently it is not supported, is it something on the roadmap?

**Comment by ross** [comment]
> Currently it is not supported, is it something on the roadmap?

Looks like [support was added to Azure itself in mid-november](https://azure.microsoft.com/en-us/blog/azure-dns-updates-caa-record-support-and-ipv6-nameservers/). It should be relatively straightforward to add the new type to the provider.

/cc @h-hwang for thoughts

**Comment by mohitsuley** [comment]
Ack. I'll put this on our backlog.

**Comment by ross** [comment]
> Just started setting up octodns and found that CAA and SOA records weren't supported. Any idea when these might get added?

SOA probably isn't going to be supported due to the inconsistencies in what, if anything, providers support editing. More info on that is in https://github.com/github/octodns/issues/39#issuecomment-303738180.

CAA is supported in general, but not (yet) by all providers. This issue is tracking adding CAA support to Azure, others already support it. There's a [table in the README](https://github.com/github/octodns#supported-providers) with the support matrix.

**Comment by silverl** [comment]
Another vote for CAA support in Azure. Thanks.

**Comment by ross** [comment]
PRs accepted. I don't have access to Azure's DNS or time to dig into it really.
