### ISSUE TITLE
Question: is it possible to ignore a subdomain?

### ISSUE THREAD

**Issue by schu** [github/octodns#203]
For example, because the subdomain is managed through a different tool (e.g. terraform) or account (to split user privileges).

If not, would you accept a patch to add support for that?

**Comment by ross** [comment]
If the sub-domain is managed as a separate zone octoDNS won't touch it if not configured to manage it as well (which it wouldn't be if you're using terraform instead.)

You may need to manage the NS records for the sub-domain in the parent with octoDNS depending on the details of the setup so that queries for `subdomain.foo.com.` know where to look for the sub-zone's records.

**Comment by schu** [comment]
That works for me, thanks @ross
