### ISSUE TITLE
Unable to import module octodns.provider.googlecloud.GoogleCloudProvider

### ISSUE THREAD

**Issue by DP-M** [github/octodns#225]
If I remove the googlecloud provider, and just use YamlProvider, and DnsMadeEasyProvider, it works as expected. 

CentOS 7, virtualenv, python2.7, installed today via pip, first time using octodns. 

config/test.yaml: 
```
---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
  googlecloud:
    class: octodns.provider.googlecloud.GoogleCloudProvider
    project: project1
    credentials_file: ~/.google_cloud_credentials_file.json
  dnsmadeeasy:
    class: octodns.provider.dnsmadeeasy.DnsMadeEasyProvider
    api_key: xxx
    secret_key: xxx
zones:
  testzone.com.:
    sources:
      - dnsmadeeasy
    targets:
      - config
      - googlecloud
```

```
(octodns) 04/05 06:34[mdp@admin1-GOOGLE octodns]$ octodns-sync --config-file config/test.yaml
2018-04-05T06:34:38  [140319841122112] INFO  Manager __init__: config_file=config/test.yaml
2018-04-05T06:34:38  [140319841122112] INFO  Manager __init__:   max_workers=1
2018-04-05T06:34:38  [140319841122112] INFO  Manager __init__:   max_workers=False
2018-04-05T06:34:38  [140319841122112] ERROR Manager _get_{}_class: Unable to import module octodns.provider.googlecloud.GoogleCloudProvider
Traceback (most recent call last):
  File "/home/mdp/octodns/lib/python2.7/site-packages/octodns/manager.py", line 154, in _get_named_class
    module = import_module(module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mdp/octodns/lib/python2.7/site-packages/octodns/provider/googlecloud.py", line 14, in <module>
    from google.cloud import dns
ImportError: No module named google.cloud
Traceback (most recent call last):
  File "/home/mdp/octodns/bin/octodns-sync", line 11, in <module>
    sys.exit(main())
  File "/home/mdp/octodns/lib/python2.7/site-packages/octodns/cmds/sync.py", line 37, in main
    manager = Manager(args.config_file)
  File "/home/mdp/octodns/lib/python2.7/site-packages/octodns/manager.py", line 98, in __init__
    _class = self._get_named_class('provider', _class)
  File "/home/mdp/octodns/lib/python2.7/site-packages/octodns/manager.py", line 158, in _get_named_class
    raise Exception('Unknown {} class: {}'.format(_type, _class))
Exception: Unknown provider class: octodns.provider.googlecloud.GoogleCloudProvider
(octodns) 04/05 06:34[mdp@admin1-GOOGLE octodns]$
```

**Comment by ross** [comment]
What version of octoDNS do you have installed?

```
(env)otter:octodns ross$ python -c 'import octodns; print(octodns.__VERSION__)'
0.9.0
```

**Comment by DP-M** [comment]
```
(octodns) 04/05 16:43[mdp@admin1-GOOGLE octodns]$ python -c 'import octodns; print(octodns.__VERSION__)'
0.9.0
```

**Comment by DP-M** [comment]
@yzguy Do I have to install the google-cloud module separately? 
provider/googlecloud.py exists, and has what appears to be reasonable content (ie: not corrupted, etc)

**Comment by ross** [comment]
This is likely due to shortcomings in the docs. AS @yzguy pointed out you'll need to install the `google-cloud` module. You can see the full list of octoDNS's dependancies in setup.cfg. I didn't want to force everyone to install every dependency regardless of which provider(s) they were going to use so the base install just includes the stuff that the core of octoDNS needs. 

We (github) have a separate repo in which we keep all of our config that installs `octodns` and the Dynect (`dyn`) & Route53 (`boto`) dependancies. 

I believe `google-cloud` was actually one of the things that lead me to go this round as it installs a boatload of packages/dependancies that only make sense ti bother with if you're going to use it.

Longer term I'm thinking about breaking up all of the providers into sub-modules so that you only install the octoDNS modules you're going to use. Those modules would depend on the core of octoDNS and any client libraries/modules they need. Deciding (and doing) that is the main thing that's keeping me from calling it 1.0 :-)

**Comment by DP-M** [comment]
Thanks @ross and @yzguy -- That was indeed it, and your logic regarding the-pile-o-modules makes sense. Maybe in the [Supported Providers](https://github.com/github/octodns#supported-providers) table, it would make sense to add a column, which at a minimum mentions providers that require additional libraries, vs those that don't. For bonus points, providing a link to that providers setup instructions could be helpful. 

For the next newb that strolls through here, this is the full list of steps for me to setup a public GCE CentOS7 image with octodns for DNSME & google cloud dns: 
```
sudo yum -y install python-pip python-devel python-setuptools
sudo pip install --upgrade pip virtualenv
virtualenv octodns
cd octodns
source bin/activate
pip install --upgrade google-cloud
pip install --upgrade octodns
Follow README instructions. 
```

Thanks!

**Comment by ckotil** [comment]
This resolved it for me:
pip install google-cloud-dns
