### ISSUE TITLE
New Patch Release

### ISSUE THREAD

**Issue by brianeclow** [github/octodns#240]
Morning,
In light of [google-cloud-python Issue 5353](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5353), could we get a patch release that includes the current master leveraging the `requirements.txt` file?

**Comment by brianeclow** [comment]
For a bit more background, I have been building a CI/CD integration with octoDNS and one of our pipelines, and this egg problem just stopped me cold without some brain surgery to my existing DNS pipeline.

**Comment by ross** [comment]
You installing the dev requirements with the old release? Otherwise I don't believe google-cloud would be getting installed. It only requires > 0.27.0 so you should still be able to pin at the same level you're pulling in octoDNS. 

I can look at cutting a release, seems like there's a few minor fixes since the last one, but I don't think it should be required to work around the google-cloud bug.
