### ISSUE TITLE
domainkey in octodns-dump

### ISSUE THREAD

**Issue by bcruik** [github/octodns#25]
I get the following error when DKIM records are unescaped when dumping from cloudflare.

For example "v=DKIM1; k=rsa; ..." fails with:
Exception: Invalid record google._domainkey.domain.com., unescaped ;
However "v=DKIM1\\; k=rsa\\; ..." works fine.
Thats regardless if quotes are around the record.

Is this a bug, just a cloudflare thing or are my domainkey records technically wrong?

**Comment by zBart** [comment]
I had the same issue, as a workaround I changed [line 102 in cloudflare.py](https://github.com/github/octodns/blob/master/octodns/provider/cloudflare.py#L102) from:
```
    _data_for_TXT = _data_for_multiple
```

To:
```
    def _data_for_TXT(self, _type, records):
        return {
            'ttl': records[0]['ttl'],
            'type': _type,
            'values': [r['content'].replace(';', '\;') for r in records],
        }
```
Which escapes the semicolons when the data is fetched. 

I don't know if this is proper behavior but it allowed me to fetch the data without having to change the record. Note that I haven't tested what happens when OctoDNS pushes the data to Cloudflare yet, so beware.

**Comment by ross** [comment]
> I don't know if this is proper behavior but it allowed me to fetch the data without having to change the record.

That looks roughly correct, at least on the right path. There's [something similar in Route53](https://github.com/github/octodns/blob/faa4630362cca9f552271f84047f78d3db0b5791/octodns/provider/route53.py#L67-L68) for dealing with `"`. 

It'll probably require a corresponding change to `_contents_for_TXT`, something like:

```python
    def _contents_for_TXT(self, record):
        for value in record.values:
            yield {'content': value.replace('\;', ';')}
```

@zBart if you want to put together a PR update the tests for that and I'll take a :eyes:, if not I'll put it on my TODO list

**Comment by ross** [comment]
Should be fixed in https://github.com/github/octodns/pull/29

**Comment by zBart** [comment]
Thanks @ross !

Would it be possible to release a new version with this fix? Or is there a way I can tell `pip` to switch to the `master` version (don't have any experience with it)?

**Comment by ross** [comment]
> Or is there a way I can tell pip to switch to the master version (don't have any experience with it)?

You can use a git URL with pip and specify a sha (recommended) or branch name (usually not a great idea since it can change out from under you)

```
-e git+ssh://git@github.com/github/octodns.git@<sha>#egg=octodns
```

I'll probably do a release before too long, but I'm waiting to see what other bugs show up and hoping to get a chance to come up with a real solution for ALIAS records first.
