### ISSUE TITLE
Revert again to setup.py for dependencies

### ISSUE THREAD

**Issue by tnir** [github/octodns#265]
@ross Per #235, what were the problems for you to keep using #139, which is crucial for Python 3 support (especially selective removing [futures package](https://pypi.org/project/futures/)).

**Comment by ross** [comment]
> @ross Per #235, what were the problems for you to keep using #139,

Don't remember specifically, but it was issues with trying to install the package with pip when it was pointed at a specific git SHA that someone else had run into and reported and we were actually running into at work. I had run into a couple smaller things previously that I had to figure out/fix as well.

> which is crucial for Python 3 support (especially selective removing futures package).

Don't agree with this. I personally have packages that use future that are functional for both 2.7 and 3. It's trivial to add a version check to setup.py that includes `futures` with 2.7 and omits it for 3.x, e.g. https://github.com/ross/requests-futures/blob/d09d7e3294b4a7c2ea2859f99ae664ac3c4fa463/setup.py#L25-L26. I generally do requirements.txt and requirements-3.x.txt or similar to solve the dev cases.

Sorry, but I don't have interest in dealing with/debugging the new style setup.cfg stuff given that I can't find any major modules that are using it and examples/help was lacking. If https://github.com/github/octodns/pull/139 had just worked I'd be up for it, but it's tough enough for me to find time to keep up with octoDNS itself and I don't want to spend what bandwidth I do have on packaging bits.

**Comment by tnir** [comment]
OK, I see. Then, I'd like to change it to use `setup.py` without `setup.cfg` for Python 3 support rather than split `requirements*.txt` files. I have time to make a patch with `extras_require`/`install_requires` in `setup.py` for Python.

Splitting `requirements.txt` to multiple files would be hard to maintain but `setup.py` without `setup.cfg` will help us avoid to waste time to struggle with new setup.cfg as well to maintain dual requirements.txt.

```
setup(
    ...
    extras_require={
        ':python_version == "2.7"': ['futures']
    }
)
```
via https://github.com/agronholm/pythonfutures

Dual "requirements.txt" files after support Python 3 will make both users and CI process harder than the simple `setup.py`.

Will you consider reviewing a patch with moving all dependencies from `requirements.txt` into `setup.py` **without** `setup.cfg`?

**Comment by ross** [comment]
> Will you consider reviewing a patch with moving all dependencies from requirements.txt into setup.py without setup.cfg?

I think the hiccup there is that what's is setup.py is the "required" stuff (base requirements of octoDNS itself, not providers), but requirements.txt includes everything you'd need to run all providers. I don't want to require users to install dozens of unneeded dependancies which is why setup.py is minimal and there's a section in the readme saying what needs to be installed for each provider. 

The 2.7 bit you have above for futures looks like it'd probably solve the setup.py 2.7 & 3.x bit. Having two requirements.txt files for requests-futures has worked fine https://github.com/ross/requests-futures so that seems like a reasonable approach here. Users & ci can easily be set up to use the correct one as they have on that project.

**Comment by tnir** [comment]
@ross Thanks. With such a policy, just started with #271

**Comment by ross** [comment]
https://github.com/github/octodns/pull/384 added py3 support
