### ISSUE TITLE
Enhanced record validation 

### ISSUE THREAD

**Issue by ross** [github/octodns#3]
Refactor validation logic to be a method on each record type and to accept a flags parameter to indicate how thoroughly to validate things beyond what's currently there.

Things like:
* ~~Ensure `values` are unique~~
* [ ] cname targets, mx, srv, etc. hostnames are resolvable
* [ ] maybe ip addresses are routable, pingable, http/https able... though not clear how it'd know what to try
* [x] `CNAME` can't coexist

**Comment by ross** [comment]
* `CNAME` aren't allowed to co-exist alongside other records

**Comment by ross** [comment]
> Ensure values are unique

That doesn't make sense. There are valid cases where you want/need to do so.

> MX & CNAME can't coexist

Done in https://github.com/github/octodns/pull/74. Also reject `CNAME`s on the root node.

**Comment by ross** [comment]
> cname targets, mx, srv, etc. hostnames are resolvable
>  maybe ip addresses are routable, pingable, http/https able... though not clear how it'd know what to try

I've decided these 2 don't make sense as "record" validations, but I would like to build tooling, e.g. `octodns-validate`, that would walk a zone and look for these types of problems. I think that's a much cleaner way to go about this. The work involved/details of doing this stuff would be too heavyweight during a normal octodns-sync/dump/etc.

**Comment by brianeclow** [comment]
I just ran into this:
 - A `cnames` cannot point to itself.

A DNS provider happily allowed us to create this condition via the web ux, however, route53 and dyn rejected it upon attempting to create the entries via octodns with the `--doit` flag.

**Comment by o-be-one** [comment]
Please also add more logs/verbosity for errors. I had to find my answers by checking other issues.
Like for "out of key" ... Or "Invalid record domain.tld., missing type" ... It's not evident at first from where the issue is. Probably you can give more informations regarding the error or give a link to GitHub issue, something like that eheh :). It will help people less friendly with Python to understand issues.

**Comment by yzguy** [comment]
https://github.com/github/octodns/issues/63 I think is related to making log messages more clear. 

There could definitely be a bit more descriptive errors, in-depth knowledge of DNS is needed to understand sometimes what went wrong, whether it be on the OctoDNS side or something that's happening because of behavior in a provider.

Thanks for the feedback!

**Comment by evaryont** [comment]
The SPF standard doesn't mention it explicitly, but a few email servers I've found reject all mail from domains with multiple SPF records. Others still iterate through all SPF records as if it was one long one when multiple are present. It seems mostly harmless as the some of the biggest email hosters (GMail, Outlook, AOL, Yahoo I know) don't care about multiple SPF records.

There is also the "rule of 10" for SPF, in which an SPF record should not generate more than 10 DNS records to fetch all of the allowed IPs. Counting the number of flags that do cause a DNS lookup (a, mx, include, etc) and erroring out when that does reach greater than 10 would be nice. However, server-side enforcement of this rule is also patchy.

**Comment by ross** [comment]
There's been lots of enhancements made to validations since it was opened, but they're by no means complete, nor with the every be. New stuff can should be added in PRs as this issue isn't serving a purpose going to close.
