### ISSUE TITLE
Add A-Name support to DNSMadeEasy Provider

### ISSUE THREAD

**Issue by fahanson** [github/octodns#304]
DNS Made Easy has a type of Alias Record called an "A-Name". Some of our infrastructure is still hosted in Heroku which requires A-Names for custom domain names. This would be a huge win for us so we can manage all our domains with OctoDNS.

**Comment by ross** [comment]
It should be possible to wire things up so that a octoDNS `ALIAS` record is mapped to an "A-name" in DNSMadeEasy. There are a few other providers that do similar types of mapping already, e.g. Cloudflare's is just a CNAME on the root. I won't have the bandwidth to look into it in the near term, but would gladly look over an PR if someone gets a chance to look into it.

**Comment by fahanson** [comment]
My Python is decent enough that I could probably take at least a first pass at something for you to look at and suggest changes on.

**Comment by fahanson** [comment]
@yzguy If you could add this that would be awesome!

**Comment by yzguy** [comment]
Sure thing @fahanson, let me check it out.
