### ISSUE TITLE
Release and release cycle of octodns

### ISSUE THREAD

**Issue by PeterDaveHello** [github/octodns#344]
Just being curious about when the next release would be and how long should we expect a new release? Currently, there are more then 10% commits are not released in any new version yet, it'll be great to have a new one, many thanks!

**Comment by ross** [comment]
> Just being curious about when the next release would be and how long should we expect a new release?

Route53Provder and DynProvider support for `dynamic` records has landed, but for the most part they haven't yet been documented so that's the main thing that needs to happen first. No specific timeline on it though. Pretty busy atm and not sure when I'll get to it. 

In the meantime newer versions can always be pulled via pip with the sha, e.g.:

```
-e git+https://git@github.com/github/octodns.git@959370b6915c6cfa698bb6dbf02d31a1ea1b9a6e#egg=octodns
```

**Comment by PeterDaveHello** [comment]
Thanks for the explanation @ross !
