### ISSUE TITLE
Feature request: Support for Constellix as a DNS provider

### ISSUE THREAD

**Issue by danielmittelman** [github/octodns#382]
I'd love it if OctoDNS supported Constellix as a DNS provider.
I tried doing it myself but the lack of documentation has driven me to give up after 3 hours

**Comment by yzguy** [comment]
Hello,

I am working on a Constellix provider here: https://github.com/yzguy/octodns/tree/constellix_provider

I have the "dump" part working, still dealing with some oddities of the provider's API, but because DNSMadeEasy also owns Constellix then a lot of that provider is directly compatible, but there are definitely differences.

Hopefully something ready by this weekend!

**Comment by yzguy** [comment]
@danielmittelman Just opened a PR #387 for this provider.

**Comment by danielmittelman** [comment]
@yzguy Wow, that's great news! Kudos for you for accomplishing that!

I've actually talked to Constellix a few weeks ago and they told me that writing a Constellix provider for OctoDNS is something that they're planning for the near future. I think it'd be helpful if you contact them and let them know of your work so that they can help you review it from their side and perhaps offer assistance/insights.

**Comment by yzguy** [comment]
@danielmittelman Actually they contacted me haha

I don't actually use Constellix so if they are aware of it, then I'd imagine/hope there might be features added to that provider from them.

Looks like the PR was merged, so give it a try!
