### ISSUE TITLE
No failure when creating an ALIAS record on route53

### ISSUE THREAD

**Issue by josvo** [github/octodns#573]
When I create an ALIAS record for ns1 and route53 at the same time, the ALIAS is created for ns1 but not for route53. There is only a warning showing up, e.g.

`2020-06-24T09:21:58  [140251713709888] DEBUG Zone changes:  skipping record=asdf.test. ALIAS - route53 does not support it`

But it succeeds:
```
`********************************************************************************
* asdf.test.
********************************************************************************
* ns1 (Ns1Provider)
*   Create Zone<asdf.test.>
*   Create <ARecord A 14400, asdf.test., ['1.2.3.4']> (config)
*   Create <AliasRecord ALIAS 14400, asdf.test., jklm.test.> (config)
*   Summary: Creates=2, Updates=0, Deletes=0, Existing Records=0
* route53 (Route53Provider)
*   Create Zone<asdf.test.>
*   Create <ARecord A 14400, asdf.test., ['1.2.3.4']> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=0

********************************************************************************`
```

The problem with this behaviour is that if you don't pay attention and especially when other records are created at the same time, it will create the ALIAS on ns1 but not on route53. 
This leads to an unwanted behaviour: You get a correct answer from NS1, but you don't get an answer from route53, what makes it hard to debug, because sometimes DNS resolution works and sometimes it doesn't. 
I can see that the records get skipped https://github.com/github/octodns/blob/ccc4d8dfc03871cf734d30347c6accb42f457f7f/octodns/provider/route53.py#L956

What would be the correct way to handle this? It is possible to make it fail instead of printing a warning, but I'm not sure if this will break other things.

**Comment by ross** [comment]
Route53 Doesn't support ALIAS semantics and thus doesn't support the record type,  https://github.com/github/octodns#supported-providers. It's Alias type is something different and only supports pointing at some types of things in the same Zone.  This is also indicated in the `SUPPORTS` property on the provider https://github.com/github/octodns/blob/ccc4d8dfc03871cf734d30347c6accb42f457f7f/octodns/provider/route53.py#L612-L613

> I can see that the records get skipped

That's on the way out of Route53 rather than pushing in, but yes. It does warn about Route53 style aliases not being supported. 

If debug logging is turned `--debug` you will see a message about skipped records https://github.com/github/octodns/blob/2c8fe957fbb738ff0868751fbb5b7766438a676f/octodns/zone.py#L177-L180. That's not at a higher level as it can get really noisy and repetitive.

The readme and/or the SUPPORTS variables will indicate what will/won't be created, as will the plan output. Things are currently working as intended.
