### ISSUE TITLE
YamlProvider git hash record insertion

### ISSUE THREAD

**Issue by phelpsw** [github/octodns#583]
A topic @acm1 and I have been discussing is how to validate a certain version of octodns yaml configs has been deployed.  A common pattern is to use git to manage these yaml configs, one thought was to modify the YamlProvider to optionally inject a TXT record containing a git hash when this feature is enabled.  Then the deployment process can monitor this record looking for a specific hash to validate the change has propagated.

In multi-provider configurations based on octodns, the serial number of the zone isn't consistently managed across providers so validating deployment by monitoring incrementing serial numbers will be provider specific and isn't clearly traceable back to a specific yaml configuration version and won't be synchronized across providers.

One additional option I can think of right now:
 - Only focus on git vs design the feature to use environment variables or a file containing the desired version number to be injected which would allow for different version control systems to be used.

I'm happy to implement this feature but I'm hoping to get some feedback on this idea before I spend time here.

**Comment by ross** [comment]
I like the idea and would use it. I'd recommend a separate provider rather adding this on top of YamlProvider. It could just be something like `GitShaSource`. You could then use it along side YamlProviders like:

```yaml
...
  myzone.com.:
    sources:
      - GitShaSource
      - YamlProviders
    targets:
...
```

There's [octodns-meta](https://github.com/github/octodns/blob/817e8bc8bd9e84b10bfc72394b36f95e6456b334/octodns/manager.py#L246-L250) already which is added by the `Manager` which allows you to test which provider was used when you do [split authority](https://github.blog/2017-04-27-enabling-split-authority-dns-with-octodns/). Maybe `octodns-sha` would make sense here? The name could be an optional parameter to the source so that it could be overriden if someone wanted to do something different.

Another option/route might be to do a `VersionSource` that instead of being specifically tied to git would allow you to pass an optional `command` to run (that defaults to something getting the git sha.) This would allow people who use something other than git to do the same or they could just do `cat VERSION-INFO` or something if they deploy out of an artifact that isn't a git repo. 

> * Only focus on git vs design the feature to use environment variables or a file containing the desired version number to be injected which would allow for different version control systems to be used.

Getting the value from an environmental variable (which I think you might be suggesting here) sounds pretty good too. Tbh that might be the most flexiable option. It could be `EnvVarSource` then and allow you to specify that env variable to pull the value from and the record name to use. Tbh that sounce the most flexible as it wouldn't be limited to just doing SHA etc. 

Happy to take a look at PRs around this and I'd probably use it...

**Comment by phelpsw** [comment]
Feature has been implemented and merged, I believe this can be closed
