### ISSUE TITLE
optional dependencies not in metadata

### ISSUE THREAD

**Issue by jayvdb** [github/octodns#607]
It looks like `edgegrid-python` is an optional dependency which isnt mentioned anywhere afaics

Edit: Ah, I see them in https://github.com/github/octodns#supported-providers

It would be better to have them in requirements-dev.txt or setup.py as "extras" (and have tests for them..).

**Comment by ross** [comment]
> It would be better to have them in requirements-dev.txt or setup.py as "extras" (and have tests for them..).

Normally all of the providers are included in `requirements.txt` and only the base requirements of octodns itself are in setup.py so that devs get everything and people who pip install octodns get the bare minimum and then can pull in the specifics they need for their setup.

If edgegird (or anything else for that matter) isn't in requirements.txt it's an oversight and PRs are welcome.

**Comment by ross** [comment]
Closing this one as a works as expected for now. https://github.com/github/octodns/issues/622 talks about how the future plan is to break up each provider into it's own module and it should be possible to have the full deps associated in that setup.
