### ISSUE TITLE
Cloudflare and "shield" records

### ISSUE THREAD

**Issue by jbergstroem** [github/octodns#65]
Cloudflare lets you "shield" (cdn/dns) A and CNAME records. This enables their cdn functionality. Seeing how the feature is embedded into the way DNS records is handled on CloudFlare, I thought I should at least bring up whether or not this belongs in octodns.

(if nothing else, a closed issue might be useful if others are thinking of the same thing)

**Comment by ross** [comment]
> least bring up whether or not this belongs in octodns.

Short answer is that I don't know. Given that it's very specific to Cloudflare it's not really in the wheelhouse of the problem octoDNS was setting out to solve, but that said if someone is just managing Cloudflare alone with octoDNS it'd be nice to have. 

I think that leaves it in a place where the answer is: maybe, someday, if/when there's a solid system for managing provider specific config. In practice that probably means it'd be a really low priority and won't land anytime soon.

**Comment by jacobleonw** [comment]
cheers @ross 

might be time for me to learn some python 🐍

**Comment by begincalendar** [comment]
@ross As a user of Cloudflare and occasionally its CDN/proxy, I find it quite unfortunate that OctoDNS doesn't support this particular CloudFlare feature (because I think OctoDNS is such a uniquely useful tool).

Having said that, although I'm not familiar with the implementation, I can appreciate that it's most likely not a simple task and understand it is of low priority.

If someone were to work on this, what approach do you think they should take?
Should the CloudFlare provider implementation be modified and the remainder of OctoDNS's API remain unchanged, or are there plans to alter the OctoDNS API to allow for provider-specific (not just CloudFlare) configuration, which should be taken into consideration?

**Comment by ross** [comment]
> Having said that, although I'm not familiar with the implementation, I can appreciate that it's most likely not a simple task and understand it is of low priority.

I don't believe it'd be too difficult, but since I haven't directly had a use for it (professionally or personally) it is a low priority for me and hasn't made it up the TODO list. The other thing preventing it from getting a higher priority is that it's provider specific and in general octoDNS is about enabling multiple providers with a single configuration. That not to say that it isn't useful for managing a single provider, it just wasn't the problem it set out to solve. 

> If someone were to work on this, what approach do you think they should take?
> Should the CloudFlare provider implementation be modified and the remainder of OctoDNS's API remain unchanged, or are there plans to alter the OctoDNS API to allow for provider-specific (not just CloudFlare) configuration, which should be taken into consideration?

There are a couple use of an `octodns` key under records for things like customizing healthchecks and specifying lenient validation for individual records. That data isn't currently stored in the record object through so it'd be "gone" by the time providers were able to take a look at it. 

I think the first step would be holding on to the `data` in the record object so that providers could later look at it. The next bit would be updating the CF provider to look for the key and do it's thing, the config might look like:

```yaml
foo:
  octodns:
    cloudflare:
      proxy: true 
  type: A
  value: 1.2.3.4
```

The provider can then manage that flag based on the "extra" info. It'd also have to make use of some of the more "advanced" bits of providers to flag records that otherwise match, but don't have the correct proxy setting, currently there are various bits of the Geo records that do this in Dyn and Route53. https://github.com/github/octodns/blob/61b30f2b41d5b209b302b0a3c1bdf8af44e8d3e0/octodns/provider/base.py#L37-L43. Beyond that it'd just be a matter of working out the kinks and getting it throughly tested (which is often the biggest part of the work.)

**Comment by ross** [comment]
> ...Could you please elaborate on that?

There will be cases where you have a record in the config and in Cloudflare's system where the values match up, but the proxied flag doesn't. octoDNS's process won't consider that a "diff" and thus won't make updating that record part of the plan and give the provider a chance to fix it.

The Cloudflare provider will have to walk over all of the records in an overridden `_extra_changes` to look for things that don't get flagged as general changes, but still need to be added to the plan for the provider to update the proxy flag. If you search around for `_extra_changes` you'll see other examples of similar cases, healthchecks that need updating in `geo` enabled records etc.
