### ISSUE TITLE
DKIM semicolon escaping with octodns-dump and NS1

### ISSUE THREAD

**Issue by blakestoddard** [github/octodns#79]
(Sorry about all of my issues with DKIM's and semicolons :( )

It looks like #34 might apply to NS1, as well? If you have not escaped the semicolon in your TXT record, NS1 will serve it back to you with it unescaped:
```
{
      "domain": "mail._domainkey.foo.com",
      "short_answers": [
        "v=DKIM1;t=y; p=<key>"
      ],
      "link": null,
      "ttl": 900,
      "tier": 1,
      "type": "TXT",
      "id": "<arbitrary record ID>"
    },
```
(from the NS1 API)

Thus resulting in the following error:
```
octodns.record.ValidationError: Invalid record mail._domainkey.foo.com.
  - unescaped ;
```

**Comment by blakestoddard** [comment]
I unfortunately don't know much Python, but I tried my hand at fixing this using the method that was done to fix it for Route53 and I'm running into an issue with it.

[Commit on my fork](https://github.com/blakestoddard/octodns/commit/f230b658c988f001ff954019d9fa2cc5ba308be2)

When I attempt a run of `octodns-sync` (sans `--doit`), every TXT and SPF record is marked as needing to be updated and all of the outputs look like such (removal of a "u" before the value begins, and an additional letter at the end that doesn't appear to be being returned by NS1 initially but exists in the record locally):
```
*   Update
*     <TxtRecord TXT 900, mail._domainkey.foo.com., [u'=DKIM1\\;p=<snip>A']> ->
*     <TxtRecord TXT 900, mail._domainkey.foo.com., ['v=DKIM1\\;p=<snip>AB']> (zones)
```

@ross am I making a dumb Python mistake somewhere?

**Comment by ross** [comment]
As of https://github.com/github/octodns/pull/74 there's a new option to dump, `--lenient` which will ignore validation on the way in. It also loosens validation when pulling down the current state of a provider during a sync. With those changes the problem you're running into shouldn't be an issue any longer, it'll just be a warning.

```
(env) sweetums:octodns ross$ PYTHONPATH=. ./octodns/cmds/dump.py --config-file=config/dev.yaml githubtest.net. ns1 --output-dir=tmp/
2017-06-27T11:20:16  [140735305896704] INFO  Manager __init__: config_file=config/dev.yaml
2017-06-27T11:20:16  [140735305896704] INFO  Manager __init__:   max_workers=4
2017-06-27T11:20:16  [140735305896704] INFO  Manager __init__:   max_workers=True
2017-06-27T11:20:17  [140735305896704] INFO  Manager dump: zone=githubtest.net., sources=()
Traceback (most recent call last):
  File "./octodns/cmds/dump.py", line 35, in <module>
    main()
  File "./octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "/Users/ross/github/octodns/octodns/manager.py", line 357, in dump
    source.populate(zone, lenient=lenient)
  File "/Users/ross/github/octodns/octodns/provider/ns1.py", line 132, in populate
    source=self, lenient=lenient)
  File "/Users/ross/github/octodns/octodns/record.py", line 115, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record txt.githubtest.net.
  - unescaped ;
(env) sweetums:octodns ross$ PYTHONPATH=. ./octodns/cmds/dump.py --config-file=config/dev.yaml githubtest.net. ns1 --output-dir=tmp/ --lenient
2017-06-27T11:22:24  [140735305896704] INFO  Manager __init__: config_file=config/dev.yaml
2017-06-27T11:22:24  [140735305896704] INFO  Manager __init__:   max_workers=4
2017-06-27T11:22:24  [140735305896704] INFO  Manager __init__:   max_workers=True
2017-06-27T11:22:24  [140735305896704] INFO  Manager dump: zone=githubtest.net., sources=()
2017-06-27T11:22:24  [140735305896704] WARNING Record Invalid record txt.githubtest.net.
  - unescaped ;
2017-06-27T11:22:24  [140735305896704] INFO  Ns1Provider[ns1] populate:   found 16 records
2017-06-27T11:22:24  [140735305896704] INFO  YamlProvider[dump] plan: desired=githubtest.net.
2017-06-27T11:22:24  [140735305896704] INFO  YamlProvider[dump] plan:   Creates=15, Updates=0, Deletes=0, Existing Records=0
2017-06-27T11:22:24  [140735305896704] INFO  YamlProvider[dump] apply: making changes
```

So the current master is probably the place to start. I'm hoping to cut a new release very soon, ideally today, but we'll see how it goes :-)

**Comment by ross** [comment]
Note you will have to "fix" the resulting config by escaping the `;` before you can use it as a source. The intention is to make it easier to get things into octoDNS, but to retain the consistency/best practices going forward.

**Comment by blakestoddard** [comment]
Awesome, thanks. `--lenient` should take care of my issue here, but I can always work back through and add the semicolons manually in the NS1 UI if need-be.

**Comment by ross** [comment]
Just a bit more follow up for people who happen across this in the future. To the best of my knowledge the `\` is required before all `;` in `TXT` records. There are definitely some providers that don't require it to be provided in their UI/API, Route53 & NS1. That said when they serve the records they always escape them, e.g.

#### Route53

<img width="986" alt="screen shot 2017-06-29 at 8 41 12 pm" src="https://user-images.githubusercontent.com/12789/27720489-928fe47c-5d0e-11e7-9840-c3747b81b4d9.png">

```
sweetums:~ ross$ dig +short TXT dkim-test.githubtest.net. @ns-1304.awsdns-35.org.
"v=DKIM1\; k=rsa\; p=foobarbaz"
```

#### NS1

<img width="927" alt="screen shot 2017-06-29 at 8 49 42 pm" src="https://user-images.githubusercontent.com/12789/27720490-9292ea00-5d0e-11e7-82d7-50b99016c604.png">

```
sweetums:~ ross$ dig +short TXT dkim-test.githubtest.net. @dns1.p04.nsone.net
"v=DKIM1\; k=rsa\; p=foobarbaz"
```

Other providers "fix" the records at the time of submission, e.g.

#### Dyn

<img width="638" alt="screen shot 2017-06-29 at 9 01 33 pm" src="https://user-images.githubusercontent.com/12789/27720491-9292ec58-5d0e-11e7-9328-b21819b204b1.png">

<img width="652" alt="screen shot 2017-06-29 at 8 59 58 pm" src="https://user-images.githubusercontent.com/12789/27720488-928f0908-5d0e-11e7-85a4-b642a40ce9e4.png">

Others still don't allow submission without the `\`. 

So as best as I can tell RFCs require `\;` so octoDNS requires them. The earlier "fix" to Route53 and DNSimple were actually a mistaken on my part, in hindsight anyway. The "real" fix was to add the `--lenient` flag to `octodns-dump`. 

It's now expected behavior that when you dump such records you'll need to add the `\` if it's not there before you'll be able to use them as a source and octoDNS will show that as a change when you go to sync, but that **should** just be bringing things into compliance. For now the change won't be pushed to Route53 & DNSimple, but I'll likely go back and revert those bits now that the lenient stuff is in place and doing things a cleaner way.

**Comment by silverl** [comment]
@ross I have a weird one. I'm trying use octodns to copy Route 53 (source) to Azure DNS (dest).

I'd gotten these two providers in sync by other means, and am now trying to adopt octodns. I'm also trying to use dnscontrol to generate the octo yaml, because I like to be able to use variables. dnscontrol doesn't have an Azure DNS provider, which is why I'm trying to use octo to copy from Route 53 to Azure DNS. Anyway...

In Azure, a TXT record with escaped semi-colons yields TWO backslashes via dig.

A TXT record without any escaping yields NO backslashes in the response from dig.

```
lsilverman@mgmt-lsilver:~$ dig +short TXT unescaped.trackabout.com @ns1-03.azure-dns.com.
"v=DKIM; k=rsa; p=1234567890"
lsilverman@mgmt-lsilver:~$ dig +short TXT escaped.trackabout.com @ns1-03.azure-dns.com.
"v=DKIM\\; k=rsa\\; p=1234567890"
lsilverman@mgmt-lsilver:~$
```

This is causing problems with the sync. Octo is refusing to read the TXT records from Azure due to the missing backslashes. But if I add backslashes, the records are invalid. Catch-22.
