### ISSUE TITLE
Is the `virtualenv` tool required?

### ISSUE THREAD

**Issue by bkane-msft** [github/octodns#796]
Hello,

I'm working to set up a development environment for `octodns` and I noticed that the `virtualenv` tool is required to run the [bootstrap script](https://github.com/octodns/octodns/blob/master/script/bootstrap). 

According to https://virtualenv.pypa.io/en/latest/ , a subset of `virtualenv`'s features has been integrated in Python's built in `venv` module. In particular, I can create a virtual environment with `python3 -m venv env`.

Would you accept a PR to replace the usage of `virtualenv` with `python3 -m venv`? It would be one less dependency needed to start using/developing `octodns`.

**Comment by ross** [comment]
Nothing explicitly requires virtualenv over another similar tool. The `script` scripts are there as a convenience, especially for those new to working with python. If you know what you're doing and want to go about things with a different setup you're free to do so. 

> According to https://virtualenv.pypa.io/en/latest/ , a subset of `virtualenv`'s features has been integrated in Python's built in `venv` module. In particular, I can create a virtual environment with `python3 -m venv env`.

Until recently we supported python 2.x so venv wasn't an option since it's not present there. 

> Would you accept a PR to replace the usage of `virtualenv` with `python3 -m venv`? It would be one less dependency needed to start using/developing `octodns`.

So long as it's supported across all of the versions of python octoDNS supports it's worth considering.

**Comment by bkane-msft** [comment]
Apologies for the potentially dumb question, but where would I find the list of Python versions supported by octoDNS? I grepped "version", "3.", and skimmed setup.py and the README without seeing anything.

**Comment by bkane-msft** [comment]
Want a PR to add a `python_requires` arg to `setup.py`? https://packaging.python.org/guides/dropping-older-python-versions/#specify-the-version-ranges-for-supported-python-distributions

**Comment by bkane-msft** [comment]
It looks like `venv` has been there [since Python 3.3](https://docs.python.org/3/library/venv.html#module-venv). Want that in the same PR as adding `python_requires`?
